title: Pangolog
email: dennis@schuppentier.org
description: >- 
  Einrollen statt aufregen!
baseurl: ""
url: "https://www.schuppentier.org"
twitter_username: dasschuppentier
github_username:  dstengele
author:
  name: Dennis

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed

