title: Pangolog
email: dennis@schuppentier.org
description: >- 
  Einrollen statt aufregen!
baseurl: "/"
url: "https://www.schuppentier.org"
twitter_username: dasschuppentier
github_username:  dstengele

theme: minima
plugins:
  - jekyll-feed

